# Main Hydra config. It composes the specific group configs below.
defaults:
  - training: convnext_small
  - model: convnext_small
  - dataset: imagenet
  - optimizer: adamw
  - attacks: adv
  - dist: default

# You can override any field on the CLI, for example:
# python run.py training.epochs=200 optimizer.weight_decay=0.1
