# Dataset settings for ImageNet
train_dir: '/storage/test/bml_group/tomerash/datasets/imagenet/train/'
eval_dir: '/storage/test/bml_group/tomerash/datasets/imagenet/val/'
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
scale: [0.08, 1.0]
ratio: [0.75, 1.3333]
hflip: True
vflip: False
